const getSongs = [
    {
        name: '盗将行',
        singer: '花粥/马晨阳',
        comments: 'Nothing To Do',
        singerImg: '/img/warehouse/singer3.jpg',
        songSrc: '/music/djx.m4a',
        lyrics: [
            { 'time': 0, 'content': '作曲: 花粥', 'next': 1 },
            { 'time': 1, 'content': '作词: 姬霄', 'next': 8 },
            { 'time': 8, 'content': '编曲 / 混音： 马雨阳', 'next': 18 },
            { 'time': 18, 'content': '劫过九重城关', 'next': 21 },
            { 'time': 21, 'content': '我座下马正酣', 'next': 23 },
            { 'time': 23, 'content': '看那轻飘飘的衣摆', 'next': 26 },
            { 'time': 26, 'content': '趁擦肩把裙掀', 'next': 29 },
            { 'time': 29, 'content': '踏遍三江六岸', 'next': 33 },
            { 'time': 33, 'content': '借刀光做船帆', 'next': 35 },
            { 'time': 35, 'content': '任露水浸透了短衫', 'next': 39 },
            { 'time': 39, 'content': '大盗睥睨四野', 'next': 43 },
            { 'time': 43, 'content': '枕风宿雪多年', 'next': 47 },
            { 'time': 47, 'content': '我与虎谋早餐', 'next': 49 },
            { 'time': 49, 'content': '拎着钓叟的鱼弦', 'next': 53 },
            { 'time': 53, 'content': '问卧龙几两钱', 'next': 55 },
            { 'time': 55, 'content': '蜀中大雨连绵', 'next': 59 },
            { 'time': 59, 'content': '关外横尸遍野', 'next': 62 },
            { 'time': 62, 'content': '你的笑像一条恶犬', 'next': 65 },
            { 'time': 65, 'content': '撞乱了我心弦', 'next': 83 },
            { 'time': 83, 'content': '谈花饮月赋闲', 'next': 85 },
            { 'time': 85, 'content': '这春宵艳阳天', 'next': 88 },
            { 'time': 88, 'content': '待到梦醒时分睁眼', 'next': 91 },
            { 'time': 91, 'content': '铁甲寒意凛冽', 'next': 94 },
            { 'time': 94, 'content': '夙愿只隔一箭', 'next': 97 },
            { 'time': 97, 'content': '故乡近似天边', 'next': 100 },
            { 'time': 100, 'content': '不知何人浅唱弄弦', 'next': 104 },
            { 'time': 104, 'content': '我彷徨不可前', 'next': 111 },
            { 'time': 111, 'content': '枕风宿雪多年', 'next': 114 },
            { 'time': 114, 'content': '我与虎谋早餐', 'next': 117 },
            { 'time': 117, 'content': '拎着钓叟的鱼弦', 'next': 120 },
            { 'time': 120, 'content': '问卧龙几两钱', 'next': 123 },
            { 'time': 123, 'content': '蜀中大雨连绵', 'next': 127 },
            { 'time': 127, 'content': '关外横尸遍野', 'next': 129 },
            { 'time': 129, 'content': '你的笑像一条恶犬', 'next': 133 },
            { 'time': 133, 'content': '撞乱我心弦', 'next': 135 },
            { 'time': 135, 'content': '烽烟万里如衔', 'next': 139 },
            { 'time': 139, 'content': '掷群雄下酒宴', 'next': 142 },
            { 'time': 142, 'content': '谢绝策勋十二转', 'next': 145 },
            { 'time': 145, 'content': '想为你窃玉簪', 'next': 148 },
            { 'time': 148, 'content': '入巷间吃汤面', 'next': 151 },
            { 'time': 151, 'content': '笑看窗边飞雪', 'next': 154 },
            { 'time': 154, 'content': '取腰间明珠弹山雀', 'next': 157 },
            { 'time': 157, 'content': '立枇杷于庭前', 'next': 165 },
            { 'time': 165, 'content': '入巷间吃汤面', 'next': 169 },
            { 'time': 169, 'content': '笑看窗边飞雪', 'next': 173 },
            { 'time': 173, 'content': '取腰间明珠弹山雀', 'next': 187 },
            { 'time': 187, 'content': '立枇杷于庭前', 'next': 198 }
        ],
        time_length: 198
    }
]

export default {
    getSongs
}
